# Generated by Django 5.1.2 on 2024-11-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_ru', models.CharField(max_length=100)),
                ('description_uz', models.TextField(max_length=2000)),
                ('description_ru', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordering_number', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('description_uz', models.TextField(max_length=2000)),
                ('description_ru', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customer_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
