# Generated by Django 5.1.2 on 2024-11-10 06:41

import apps.general.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='general/image/')),
                ('banner', models.ImageField(upload_to='general/banner/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13, validators=[apps.general.validate.phone_number_validate])),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('work_start_day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1)),
                ('work_end_day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=6)),
                ('work_start_time', models.TimeField()),
                ('work_end_time', models.TimeField()),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
            ],
        ),
    ]
